### PR TITLE
Add & sync download subpages

### LINKED ISSUE #129: Download Subpages
Here's the proposed design for the download subpages: Releases, Beta/Nightly, Source Code, Counter that @beafialho, @critterverse, and I have worked on [this file](https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du/Home-%26-Download-Pages?node-id=2093%3A22538).

I'll share the proposals for the desktop and mobile pages and mention some aspects of the design that could be categorized as 'nice to have'. At the end of the issue I'll add some notes about the navigation of these internal pages:

### Releases 

image

image

image

### Nice to have

- Instead of listing every release on the same page, older releases could be accessed through a list at the bottom of the page. We could either load each table under the Past releases section or have a separate page per version.
- Each major release is identified with both the version number and its code name.

---

### Beta/Nightly

image

---

### Counter

image

Something we could explore on this page is a smoother transition between numbers. We could also review the font we chose and use a monospaced one so the numbers stay in the same position as the numbers increase.

---

### Source code

image

---

### Navigation

image

The other challenging aspect of these designs are the subnavigations: on smaller viewports our proposal is for the right-side lists to collapse into dropdowns.

---

[Figma file](https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du/Home-%26-Download-Pages?node-id=2093%3A22538) with the designs.

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #129 — This branch has all the download subpages in one place. This contains #132 & #134, and uses https://github.com/WordPress/wporg-parent-2021/pull/48. 

This enables the syncing for all 4 download subpages: [Releases](https://wordpress.org/download/releases/), [Nightly](https://wordpress.org/download/beta-nightly/), [Counter](https://wordpress.org/download/counter/), [Source](https://wordpress.org/download/source/). Once we merge this, the new design can be enabled on these pages.

There was discussion about the subnavigation bar on #129 — I've added a basic iteration but the actual alignment can be iterated on in the editor after merge, if necessary. 

### Screenshots

| Beta/Nightly | Counter | Releases | Source |
|--------------|---------|----------|--------|
| beta-desktop | counter-desktop | releases-desktop | source-desktop |
| beta-mobile | counter-mobile | releases-mobile | source-mobile |

Note, the above screenshots were taken before the mobile nav button was updated to use the down-chevron - it looks like this now:
Screen Shot 2022-10-14 at 4 55 38 PM

<table>
<thead>
<tr>
<th colspan="2">Mobile "dropdown" style nav open</th>
</tr>
</thead>
<tbody>
<tr>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/541093/195941796-9858e665-dcf4-4838-80a9-954dadea942c.png">source-mobile-nav-open</a></td>
<td><a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/541093/195941799-d1c920fc-d6ab-46ee-be36-cb87a4552229.png">counter-mobile-nav-open</a></td>
</tr>
</tbody>
</table>

### How to test the changes in this Pull Request:

Visit the 4 download subpages on your local site.

### CODE REVIEW

**Comment by ryelle** [comment]
All the code parts have been reviewed in other PRs, so the only this needs is a design review. Feel free to tag in any other designers who should be involved.

Hopefully if there's anything minor (or anything in the content), we can tweak that in the editor after merge, and re-sync the content.

**Comment by jasmussen** [comment]
At a glance, looks good to me! The download counter on mobile may look a bit tall, in how it appears to push some of the footer links to be in an awkward place mid-fold, but perhaps that's related to the adminbar? Probably fine.

**Comment by javierarce** [comment]
A minor thing that could be tweaked after the merge: if possible, I would just reduce the font size of the "Number of WordPress 6.0 downloads" and increase the margin between that line and the counter to get closer to the original design. 

The rest looks good to me ✨

**Comment by ryelle** [comment]
@jasmussen @javierarce I think you can tweak those things once I've deployed this, since the issues you've raised can be fixed in the editor. Once you've got it the way you want, I can re-sync the patterns.

**Pull request merged**
