### PR TITLE
Add shortcodes for common dynamic numbers

### LINKED ISSUE #10: Create a shortcode for `WP_MARKET_SHARE`
This is a single defined constant that provides the current WP market share (ex, 43%). In `wporg-main`, this is used to build strings, so that they don't need to be re-translated every time the percentage changes. It also keeps the value defined in one place, so we don't end up with 40% in one place, and 43% in another.

```php
printf(
	/* translators: WordPress market share: 39 - Note: The following percent sign is '%%' for escaping purposes; */
	esc_html__( 'Use the software that powers over %s%% of the web.', 'wporg' ),
	esc_html( number_format_i18n( WP_MARKET_SHARE ) )
);
```

How should we handle this for content entered in the block editor?

### PR DESCRIPTION
**Pull request by dd32**
This adds ~three~ _a few_ shortcodes for various data-points:
 - `[market_share]` the value of `WP_MARKET_SHARE` including the %, defaulting to `43%`
 - `[plugin_count]` the value of `WP_PLUGIN_COUNT ` formatted to the locale number format, defaulting to `55,000`
 - `[latest_version]` the value of `WP_CORE_LATEST_RELEASE`, defaulting to the current `$wp_version` for localhost test installs. (+rosetta support)
 - `[download_link]` and `[download_link type="tar.gz"]` for the latest download link, with Rosetta support.
 - `[recommended_php]` as defined by servehappy https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/servehappy-config.php

In #10 `$meetups` is referenced, but wasn't previously displayed and doesn't appear in the [latest mockups](https://make.wordpress.org/design/2022/07/27/project-update-wordpress-org-homepage-and-download-page-mockups/), so I've skipped that. 

See #8.
Fixes #10.

Props <username>, <username>

### How to test the changes in this Pull Request:

1. Apply
2. Edit content
3. View content

### CODE REVIEW

**Comment by dd32** [comment]
With 87853bb this should also handle the immediate need for #8 as well.

**Comment by dd32** [comment]
> [recommended_php] as defined by servehappy

We might also want/need to define `[recommended_mysql_version]` and `[recommended_mariadb_version]`..

**Review by ryelle — APPROVED** [review]
Looks good 👍🏻

**Comment by ryelle** [comment]
> We might also want/need to define [recommended_mysql_version] and [recommended_mariadb_version]

The new page content does use those values, so yeah, it would be a good addition if they're available

**Comment by dd32** [comment]
>  it would be a good addition if they're available

I mean, they're not, but a shortcode that returns a static string is easy to do, and will remove the need for translation updates in the future :)

**Pull request merged**
